{
    "name": "API : CRM : Script",
    "version": "19.0.1.5",
    "category": "CRM",
    "summary": "Sync Bridging Africa jobs to Odoo CRM + Auto-invoice workflow",
    "description": "Bridging Africa API Integration with Full Automation",
    "author": "Digital Information Solutions",
    "website": "bridging-africa.com",
    "company": "Sesani Group",
    "license": "LGPL-3",
    "sequence": 1,
    "depends": [
        "base",
        "crm",
        "sale",
        "account",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/data.xml",
        "data/automation_cron.xml",
        "data/helpdesk_cron.xml",
        "data/server_actions.xml",
        "views/crm_lead.xml",
        "views/crm_automation_views.xml",
        "views/helpdesk_ticket_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
